environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g pnpm
  - pnpm install
test_script:
  - npm test
build: off
